server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* ^/api/clientes {
        rewrite ^/api/clientes(/.+?)/?$ /clientes$1 break;
        rewrite ^/api/clientes/?$ /clientes break;
        proxy_pass http://ms-clientes:8081;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location ~* ^/api/cuentas {
        rewrite ^/api/cuentas(/.+?)/?$ /cuentas$1 break;
        rewrite ^/api/cuentas/?$ /cuentas break;
        proxy_pass http://ms-cuentas:8082;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location ~* ^/api/movimientos {
        rewrite ^/api/movimientos(/.+?)/?$ /movimientos$1 break;
        rewrite ^/api/movimientos/?$ /movimientos break;
        proxy_pass http://ms-cuentas:8082;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location ~* ^/api/reportes {
        rewrite ^/api/reportes(/.+?)/?$ /reportes$1 break;
        rewrite ^/api/reportes/?$ /reportes break;
        proxy_pass http://ms-cuentas:8082;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
